/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformUserItemWrapper struct for PlatformUserItemWrapper
type PlatformUserItemWrapper struct {
	Items *[]PlatformUserItem `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewPlatformUserItemWrapper instantiates a new PlatformUserItemWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformUserItemWrapper() *PlatformUserItemWrapper {
	this := PlatformUserItemWrapper{}
	return &this
}

// NewPlatformUserItemWrapperWithDefaults instantiates a new PlatformUserItemWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformUserItemWrapperWithDefaults() *PlatformUserItemWrapper {
	this := PlatformUserItemWrapper{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PlatformUserItemWrapper) GetItems() []PlatformUserItem {
	if o == nil || o.Items == nil {
		var ret []PlatformUserItem
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformUserItemWrapper) GetItemsOk() (*[]PlatformUserItem, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PlatformUserItemWrapper) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PlatformUserItem and assigns it to the Items field.
func (o *PlatformUserItemWrapper) SetItems(v []PlatformUserItem) {
	o.Items = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *PlatformUserItemWrapper) GetPagination() Pagination {
	if o == nil || o.Pagination == nil {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformUserItemWrapper) GetPaginationOk() (*Pagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *PlatformUserItemWrapper) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *PlatformUserItemWrapper) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o PlatformUserItemWrapper) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformUserItemWrapper struct {
	value *PlatformUserItemWrapper
	isSet bool
}

func (v NullablePlatformUserItemWrapper) Get() *PlatformUserItemWrapper {
	return v.value
}

func (v *NullablePlatformUserItemWrapper) Set(val *PlatformUserItemWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformUserItemWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformUserItemWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformUserItemWrapper(val *PlatformUserItemWrapper) *NullablePlatformUserItemWrapper {
	return &NullablePlatformUserItemWrapper{value: val, isSet: true}
}

func (v NullablePlatformUserItemWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformUserItemWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


