/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
	"time"
)

// PlatformNgoLegal struct for PlatformNgoLegal
type PlatformNgoLegal struct {
	Token *string `json:"token,omitempty"`
	Firstname *string `json:"firstname,omitempty"`
	Lastname *string `json:"lastname,omitempty"`
	Nid *string `json:"nid,omitempty"`
	Brithday *time.Time `json:"brithday,omitempty"`
	Nationality *string `json:"nationality,omitempty"`
	Residence *string `json:"residence,omitempty"`
	Email *string `json:"email,omitempty"`
	Address *PlatformNgoLegalAddress `json:"address,omitempty"`
}

// NewPlatformNgoLegal instantiates a new PlatformNgoLegal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformNgoLegal() *PlatformNgoLegal {
	this := PlatformNgoLegal{}
	return &this
}

// NewPlatformNgoLegalWithDefaults instantiates a new PlatformNgoLegal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformNgoLegalWithDefaults() *PlatformNgoLegal {
	this := PlatformNgoLegal{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PlatformNgoLegal) SetToken(v string) {
	o.Token = &v
}

// GetFirstname returns the Firstname field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetFirstname() string {
	if o == nil || o.Firstname == nil {
		var ret string
		return ret
	}
	return *o.Firstname
}

// GetFirstnameOk returns a tuple with the Firstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetFirstnameOk() (*string, bool) {
	if o == nil || o.Firstname == nil {
		return nil, false
	}
	return o.Firstname, true
}

// HasFirstname returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasFirstname() bool {
	if o != nil && o.Firstname != nil {
		return true
	}

	return false
}

// SetFirstname gets a reference to the given string and assigns it to the Firstname field.
func (o *PlatformNgoLegal) SetFirstname(v string) {
	o.Firstname = &v
}

// GetLastname returns the Lastname field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetLastname() string {
	if o == nil || o.Lastname == nil {
		var ret string
		return ret
	}
	return *o.Lastname
}

// GetLastnameOk returns a tuple with the Lastname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetLastnameOk() (*string, bool) {
	if o == nil || o.Lastname == nil {
		return nil, false
	}
	return o.Lastname, true
}

// HasLastname returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasLastname() bool {
	if o != nil && o.Lastname != nil {
		return true
	}

	return false
}

// SetLastname gets a reference to the given string and assigns it to the Lastname field.
func (o *PlatformNgoLegal) SetLastname(v string) {
	o.Lastname = &v
}

// GetNid returns the Nid field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetNid() string {
	if o == nil || o.Nid == nil {
		var ret string
		return ret
	}
	return *o.Nid
}

// GetNidOk returns a tuple with the Nid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetNidOk() (*string, bool) {
	if o == nil || o.Nid == nil {
		return nil, false
	}
	return o.Nid, true
}

// HasNid returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasNid() bool {
	if o != nil && o.Nid != nil {
		return true
	}

	return false
}

// SetNid gets a reference to the given string and assigns it to the Nid field.
func (o *PlatformNgoLegal) SetNid(v string) {
	o.Nid = &v
}

// GetBrithday returns the Brithday field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetBrithday() time.Time {
	if o == nil || o.Brithday == nil {
		var ret time.Time
		return ret
	}
	return *o.Brithday
}

// GetBrithdayOk returns a tuple with the Brithday field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetBrithdayOk() (*time.Time, bool) {
	if o == nil || o.Brithday == nil {
		return nil, false
	}
	return o.Brithday, true
}

// HasBrithday returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasBrithday() bool {
	if o != nil && o.Brithday != nil {
		return true
	}

	return false
}

// SetBrithday gets a reference to the given time.Time and assigns it to the Brithday field.
func (o *PlatformNgoLegal) SetBrithday(v time.Time) {
	o.Brithday = &v
}

// GetNationality returns the Nationality field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetNationality() string {
	if o == nil || o.Nationality == nil {
		var ret string
		return ret
	}
	return *o.Nationality
}

// GetNationalityOk returns a tuple with the Nationality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetNationalityOk() (*string, bool) {
	if o == nil || o.Nationality == nil {
		return nil, false
	}
	return o.Nationality, true
}

// HasNationality returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasNationality() bool {
	if o != nil && o.Nationality != nil {
		return true
	}

	return false
}

// SetNationality gets a reference to the given string and assigns it to the Nationality field.
func (o *PlatformNgoLegal) SetNationality(v string) {
	o.Nationality = &v
}

// GetResidence returns the Residence field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetResidence() string {
	if o == nil || o.Residence == nil {
		var ret string
		return ret
	}
	return *o.Residence
}

// GetResidenceOk returns a tuple with the Residence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetResidenceOk() (*string, bool) {
	if o == nil || o.Residence == nil {
		return nil, false
	}
	return o.Residence, true
}

// HasResidence returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasResidence() bool {
	if o != nil && o.Residence != nil {
		return true
	}

	return false
}

// SetResidence gets a reference to the given string and assigns it to the Residence field.
func (o *PlatformNgoLegal) SetResidence(v string) {
	o.Residence = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *PlatformNgoLegal) SetEmail(v string) {
	o.Email = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *PlatformNgoLegal) GetAddress() PlatformNgoLegalAddress {
	if o == nil || o.Address == nil {
		var ret PlatformNgoLegalAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoLegal) GetAddressOk() (*PlatformNgoLegalAddress, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *PlatformNgoLegal) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given PlatformNgoLegalAddress and assigns it to the Address field.
func (o *PlatformNgoLegal) SetAddress(v PlatformNgoLegalAddress) {
	o.Address = &v
}

func (o PlatformNgoLegal) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Firstname != nil {
		toSerialize["firstname"] = o.Firstname
	}
	if o.Lastname != nil {
		toSerialize["lastname"] = o.Lastname
	}
	if o.Nid != nil {
		toSerialize["nid"] = o.Nid
	}
	if o.Brithday != nil {
		toSerialize["brithday"] = o.Brithday
	}
	if o.Nationality != nil {
		toSerialize["nationality"] = o.Nationality
	}
	if o.Residence != nil {
		toSerialize["residence"] = o.Residence
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformNgoLegal struct {
	value *PlatformNgoLegal
	isSet bool
}

func (v NullablePlatformNgoLegal) Get() *PlatformNgoLegal {
	return v.value
}

func (v *NullablePlatformNgoLegal) Set(val *PlatformNgoLegal) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformNgoLegal) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformNgoLegal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformNgoLegal(val *PlatformNgoLegal) *NullablePlatformNgoLegal {
	return &NullablePlatformNgoLegal{value: val, isSet: true}
}

func (v NullablePlatformNgoLegal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformNgoLegal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


