/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformCampaignItem struct for PlatformCampaignItem
type PlatformCampaignItem struct {
	Token *string `json:"token,omitempty"`
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Vouchers *int32 `json:"vouchers,omitempty"`
	Budget *float64 `json:"budget,omitempty"`
	Status *string `json:"status,omitempty"`
	PrimaryImageToken *string `json:"primaryImageToken,omitempty"`
}

// NewPlatformCampaignItem instantiates a new PlatformCampaignItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformCampaignItem() *PlatformCampaignItem {
	this := PlatformCampaignItem{}
	return &this
}

// NewPlatformCampaignItemWithDefaults instantiates a new PlatformCampaignItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformCampaignItemWithDefaults() *PlatformCampaignItem {
	this := PlatformCampaignItem{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PlatformCampaignItem) SetToken(v string) {
	o.Token = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlatformCampaignItem) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PlatformCampaignItem) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlatformCampaignItem) SetDescription(v string) {
	o.Description = &v
}

// GetVouchers returns the Vouchers field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetVouchers() int32 {
	if o == nil || o.Vouchers == nil {
		var ret int32
		return ret
	}
	return *o.Vouchers
}

// GetVouchersOk returns a tuple with the Vouchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetVouchersOk() (*int32, bool) {
	if o == nil || o.Vouchers == nil {
		return nil, false
	}
	return o.Vouchers, true
}

// HasVouchers returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasVouchers() bool {
	if o != nil && o.Vouchers != nil {
		return true
	}

	return false
}

// SetVouchers gets a reference to the given int32 and assigns it to the Vouchers field.
func (o *PlatformCampaignItem) SetVouchers(v int32) {
	o.Vouchers = &v
}

// GetBudget returns the Budget field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetBudget() float64 {
	if o == nil || o.Budget == nil {
		var ret float64
		return ret
	}
	return *o.Budget
}

// GetBudgetOk returns a tuple with the Budget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetBudgetOk() (*float64, bool) {
	if o == nil || o.Budget == nil {
		return nil, false
	}
	return o.Budget, true
}

// HasBudget returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasBudget() bool {
	if o != nil && o.Budget != nil {
		return true
	}

	return false
}

// SetBudget gets a reference to the given float64 and assigns it to the Budget field.
func (o *PlatformCampaignItem) SetBudget(v float64) {
	o.Budget = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PlatformCampaignItem) SetStatus(v string) {
	o.Status = &v
}

// GetPrimaryImageToken returns the PrimaryImageToken field value if set, zero value otherwise.
func (o *PlatformCampaignItem) GetPrimaryImageToken() string {
	if o == nil || o.PrimaryImageToken == nil {
		var ret string
		return ret
	}
	return *o.PrimaryImageToken
}

// GetPrimaryImageTokenOk returns a tuple with the PrimaryImageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItem) GetPrimaryImageTokenOk() (*string, bool) {
	if o == nil || o.PrimaryImageToken == nil {
		return nil, false
	}
	return o.PrimaryImageToken, true
}

// HasPrimaryImageToken returns a boolean if a field has been set.
func (o *PlatformCampaignItem) HasPrimaryImageToken() bool {
	if o != nil && o.PrimaryImageToken != nil {
		return true
	}

	return false
}

// SetPrimaryImageToken gets a reference to the given string and assigns it to the PrimaryImageToken field.
func (o *PlatformCampaignItem) SetPrimaryImageToken(v string) {
	o.PrimaryImageToken = &v
}

func (o PlatformCampaignItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Vouchers != nil {
		toSerialize["vouchers"] = o.Vouchers
	}
	if o.Budget != nil {
		toSerialize["budget"] = o.Budget
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.PrimaryImageToken != nil {
		toSerialize["primaryImageToken"] = o.PrimaryImageToken
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformCampaignItem struct {
	value *PlatformCampaignItem
	isSet bool
}

func (v NullablePlatformCampaignItem) Get() *PlatformCampaignItem {
	return v.value
}

func (v *NullablePlatformCampaignItem) Set(val *PlatformCampaignItem) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformCampaignItem) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformCampaignItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformCampaignItem(val *PlatformCampaignItem) *NullablePlatformCampaignItem {
	return &NullablePlatformCampaignItem{value: val, isSet: true}
}

func (v NullablePlatformCampaignItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformCampaignItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


