/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformVoucherItemWrapper struct for PlatformVoucherItemWrapper
type PlatformVoucherItemWrapper struct {
	Items *[]PlatformVoucherItem `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewPlatformVoucherItemWrapper instantiates a new PlatformVoucherItemWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformVoucherItemWrapper() *PlatformVoucherItemWrapper {
	this := PlatformVoucherItemWrapper{}
	return &this
}

// NewPlatformVoucherItemWrapperWithDefaults instantiates a new PlatformVoucherItemWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformVoucherItemWrapperWithDefaults() *PlatformVoucherItemWrapper {
	this := PlatformVoucherItemWrapper{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PlatformVoucherItemWrapper) GetItems() []PlatformVoucherItem {
	if o == nil || o.Items == nil {
		var ret []PlatformVoucherItem
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformVoucherItemWrapper) GetItemsOk() (*[]PlatformVoucherItem, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PlatformVoucherItemWrapper) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PlatformVoucherItem and assigns it to the Items field.
func (o *PlatformVoucherItemWrapper) SetItems(v []PlatformVoucherItem) {
	o.Items = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *PlatformVoucherItemWrapper) GetPagination() Pagination {
	if o == nil || o.Pagination == nil {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformVoucherItemWrapper) GetPaginationOk() (*Pagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *PlatformVoucherItemWrapper) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *PlatformVoucherItemWrapper) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o PlatformVoucherItemWrapper) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformVoucherItemWrapper struct {
	value *PlatformVoucherItemWrapper
	isSet bool
}

func (v NullablePlatformVoucherItemWrapper) Get() *PlatformVoucherItemWrapper {
	return v.value
}

func (v *NullablePlatformVoucherItemWrapper) Set(val *PlatformVoucherItemWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformVoucherItemWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformVoucherItemWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformVoucherItemWrapper(val *PlatformVoucherItemWrapper) *NullablePlatformVoucherItemWrapper {
	return &NullablePlatformVoucherItemWrapper{value: val, isSet: true}
}

func (v NullablePlatformVoucherItemWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformVoucherItemWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


