/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
	"time"
)

// PlatformCampaign struct for PlatformCampaign
type PlatformCampaign struct {
	Token *string `json:"token,omitempty"`
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Startdate *time.Time `json:"startdate,omitempty"`
	Enddate *time.Time `json:"enddate,omitempty"`
	PrimaryImageToken *string `json:"primaryImageToken,omitempty"`
	SecondaryImageToken *string `json:"secondaryImageToken,omitempty"`
	VideoUrl *string `json:"videoUrl,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewPlatformCampaign instantiates a new PlatformCampaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformCampaign() *PlatformCampaign {
	this := PlatformCampaign{}
	return &this
}

// NewPlatformCampaignWithDefaults instantiates a new PlatformCampaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformCampaignWithDefaults() *PlatformCampaign {
	this := PlatformCampaign{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PlatformCampaign) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PlatformCampaign) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PlatformCampaign) SetToken(v string) {
	o.Token = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlatformCampaign) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlatformCampaign) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlatformCampaign) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PlatformCampaign) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PlatformCampaign) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PlatformCampaign) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlatformCampaign) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlatformCampaign) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlatformCampaign) SetDescription(v string) {
	o.Description = &v
}

// GetStartdate returns the Startdate field value if set, zero value otherwise.
func (o *PlatformCampaign) GetStartdate() time.Time {
	if o == nil || o.Startdate == nil {
		var ret time.Time
		return ret
	}
	return *o.Startdate
}

// GetStartdateOk returns a tuple with the Startdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetStartdateOk() (*time.Time, bool) {
	if o == nil || o.Startdate == nil {
		return nil, false
	}
	return o.Startdate, true
}

// HasStartdate returns a boolean if a field has been set.
func (o *PlatformCampaign) HasStartdate() bool {
	if o != nil && o.Startdate != nil {
		return true
	}

	return false
}

// SetStartdate gets a reference to the given time.Time and assigns it to the Startdate field.
func (o *PlatformCampaign) SetStartdate(v time.Time) {
	o.Startdate = &v
}

// GetEnddate returns the Enddate field value if set, zero value otherwise.
func (o *PlatformCampaign) GetEnddate() time.Time {
	if o == nil || o.Enddate == nil {
		var ret time.Time
		return ret
	}
	return *o.Enddate
}

// GetEnddateOk returns a tuple with the Enddate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetEnddateOk() (*time.Time, bool) {
	if o == nil || o.Enddate == nil {
		return nil, false
	}
	return o.Enddate, true
}

// HasEnddate returns a boolean if a field has been set.
func (o *PlatformCampaign) HasEnddate() bool {
	if o != nil && o.Enddate != nil {
		return true
	}

	return false
}

// SetEnddate gets a reference to the given time.Time and assigns it to the Enddate field.
func (o *PlatformCampaign) SetEnddate(v time.Time) {
	o.Enddate = &v
}

// GetPrimaryImageToken returns the PrimaryImageToken field value if set, zero value otherwise.
func (o *PlatformCampaign) GetPrimaryImageToken() string {
	if o == nil || o.PrimaryImageToken == nil {
		var ret string
		return ret
	}
	return *o.PrimaryImageToken
}

// GetPrimaryImageTokenOk returns a tuple with the PrimaryImageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetPrimaryImageTokenOk() (*string, bool) {
	if o == nil || o.PrimaryImageToken == nil {
		return nil, false
	}
	return o.PrimaryImageToken, true
}

// HasPrimaryImageToken returns a boolean if a field has been set.
func (o *PlatformCampaign) HasPrimaryImageToken() bool {
	if o != nil && o.PrimaryImageToken != nil {
		return true
	}

	return false
}

// SetPrimaryImageToken gets a reference to the given string and assigns it to the PrimaryImageToken field.
func (o *PlatformCampaign) SetPrimaryImageToken(v string) {
	o.PrimaryImageToken = &v
}

// GetSecondaryImageToken returns the SecondaryImageToken field value if set, zero value otherwise.
func (o *PlatformCampaign) GetSecondaryImageToken() string {
	if o == nil || o.SecondaryImageToken == nil {
		var ret string
		return ret
	}
	return *o.SecondaryImageToken
}

// GetSecondaryImageTokenOk returns a tuple with the SecondaryImageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetSecondaryImageTokenOk() (*string, bool) {
	if o == nil || o.SecondaryImageToken == nil {
		return nil, false
	}
	return o.SecondaryImageToken, true
}

// HasSecondaryImageToken returns a boolean if a field has been set.
func (o *PlatformCampaign) HasSecondaryImageToken() bool {
	if o != nil && o.SecondaryImageToken != nil {
		return true
	}

	return false
}

// SetSecondaryImageToken gets a reference to the given string and assigns it to the SecondaryImageToken field.
func (o *PlatformCampaign) SetSecondaryImageToken(v string) {
	o.SecondaryImageToken = &v
}

// GetVideoUrl returns the VideoUrl field value if set, zero value otherwise.
func (o *PlatformCampaign) GetVideoUrl() string {
	if o == nil || o.VideoUrl == nil {
		var ret string
		return ret
	}
	return *o.VideoUrl
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetVideoUrlOk() (*string, bool) {
	if o == nil || o.VideoUrl == nil {
		return nil, false
	}
	return o.VideoUrl, true
}

// HasVideoUrl returns a boolean if a field has been set.
func (o *PlatformCampaign) HasVideoUrl() bool {
	if o != nil && o.VideoUrl != nil {
		return true
	}

	return false
}

// SetVideoUrl gets a reference to the given string and assigns it to the VideoUrl field.
func (o *PlatformCampaign) SetVideoUrl(v string) {
	o.VideoUrl = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PlatformCampaign) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaign) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PlatformCampaign) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PlatformCampaign) SetStatus(v string) {
	o.Status = &v
}

func (o PlatformCampaign) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Startdate != nil {
		toSerialize["startdate"] = o.Startdate
	}
	if o.Enddate != nil {
		toSerialize["enddate"] = o.Enddate
	}
	if o.PrimaryImageToken != nil {
		toSerialize["primaryImageToken"] = o.PrimaryImageToken
	}
	if o.SecondaryImageToken != nil {
		toSerialize["secondaryImageToken"] = o.SecondaryImageToken
	}
	if o.VideoUrl != nil {
		toSerialize["videoUrl"] = o.VideoUrl
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformCampaign struct {
	value *PlatformCampaign
	isSet bool
}

func (v NullablePlatformCampaign) Get() *PlatformCampaign {
	return v.value
}

func (v *NullablePlatformCampaign) Set(val *PlatformCampaign) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformCampaign(val *PlatformCampaign) *NullablePlatformCampaign {
	return &NullablePlatformCampaign{value: val, isSet: true}
}

func (v NullablePlatformCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


