/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformTopic struct for PlatformTopic
type PlatformTopic struct {
	Token *string `json:"token,omitempty"`
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	LogoToken *string `json:"logoToken,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewPlatformTopic instantiates a new PlatformTopic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformTopic() *PlatformTopic {
	this := PlatformTopic{}
	return &this
}

// NewPlatformTopicWithDefaults instantiates a new PlatformTopic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformTopicWithDefaults() *PlatformTopic {
	this := PlatformTopic{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PlatformTopic) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformTopic) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PlatformTopic) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PlatformTopic) SetToken(v string) {
	o.Token = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlatformTopic) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformTopic) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlatformTopic) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlatformTopic) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PlatformTopic) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformTopic) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PlatformTopic) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PlatformTopic) SetTitle(v string) {
	o.Title = &v
}

// GetLogoToken returns the LogoToken field value if set, zero value otherwise.
func (o *PlatformTopic) GetLogoToken() string {
	if o == nil || o.LogoToken == nil {
		var ret string
		return ret
	}
	return *o.LogoToken
}

// GetLogoTokenOk returns a tuple with the LogoToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformTopic) GetLogoTokenOk() (*string, bool) {
	if o == nil || o.LogoToken == nil {
		return nil, false
	}
	return o.LogoToken, true
}

// HasLogoToken returns a boolean if a field has been set.
func (o *PlatformTopic) HasLogoToken() bool {
	if o != nil && o.LogoToken != nil {
		return true
	}

	return false
}

// SetLogoToken gets a reference to the given string and assigns it to the LogoToken field.
func (o *PlatformTopic) SetLogoToken(v string) {
	o.LogoToken = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlatformTopic) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformTopic) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlatformTopic) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlatformTopic) SetDescription(v string) {
	o.Description = &v
}

func (o PlatformTopic) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.LogoToken != nil {
		toSerialize["logoToken"] = o.LogoToken
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformTopic struct {
	value *PlatformTopic
	isSet bool
}

func (v NullablePlatformTopic) Get() *PlatformTopic {
	return v.value
}

func (v *NullablePlatformTopic) Set(val *PlatformTopic) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformTopic) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformTopic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformTopic(val *PlatformTopic) *NullablePlatformTopic {
	return &NullablePlatformTopic{value: val, isSet: true}
}

func (v NullablePlatformTopic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformTopic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


