/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformProjectItem struct for PlatformProjectItem
type PlatformProjectItem struct {
	Token *string `json:"token,omitempty"`
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Status *string `json:"status,omitempty"`
	PrimaryImageToken *string `json:"primaryImageToken,omitempty"`
	Country *string `json:"country,omitempty"`
	Budget *float64 `json:"budget,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// NewPlatformProjectItem instantiates a new PlatformProjectItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformProjectItem() *PlatformProjectItem {
	this := PlatformProjectItem{}
	return &this
}

// NewPlatformProjectItemWithDefaults instantiates a new PlatformProjectItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformProjectItemWithDefaults() *PlatformProjectItem {
	this := PlatformProjectItem{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PlatformProjectItem) SetToken(v string) {
	o.Token = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlatformProjectItem) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PlatformProjectItem) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlatformProjectItem) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PlatformProjectItem) SetStatus(v string) {
	o.Status = &v
}

// GetPrimaryImageToken returns the PrimaryImageToken field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetPrimaryImageToken() string {
	if o == nil || o.PrimaryImageToken == nil {
		var ret string
		return ret
	}
	return *o.PrimaryImageToken
}

// GetPrimaryImageTokenOk returns a tuple with the PrimaryImageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetPrimaryImageTokenOk() (*string, bool) {
	if o == nil || o.PrimaryImageToken == nil {
		return nil, false
	}
	return o.PrimaryImageToken, true
}

// HasPrimaryImageToken returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasPrimaryImageToken() bool {
	if o != nil && o.PrimaryImageToken != nil {
		return true
	}

	return false
}

// SetPrimaryImageToken gets a reference to the given string and assigns it to the PrimaryImageToken field.
func (o *PlatformProjectItem) SetPrimaryImageToken(v string) {
	o.PrimaryImageToken = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *PlatformProjectItem) SetCountry(v string) {
	o.Country = &v
}

// GetBudget returns the Budget field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetBudget() float64 {
	if o == nil || o.Budget == nil {
		var ret float64
		return ret
	}
	return *o.Budget
}

// GetBudgetOk returns a tuple with the Budget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetBudgetOk() (*float64, bool) {
	if o == nil || o.Budget == nil {
		return nil, false
	}
	return o.Budget, true
}

// HasBudget returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasBudget() bool {
	if o != nil && o.Budget != nil {
		return true
	}

	return false
}

// SetBudget gets a reference to the given float64 and assigns it to the Budget field.
func (o *PlatformProjectItem) SetBudget(v float64) {
	o.Budget = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PlatformProjectItem) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformProjectItem) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PlatformProjectItem) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *PlatformProjectItem) SetCurrency(v string) {
	o.Currency = &v
}

func (o PlatformProjectItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.PrimaryImageToken != nil {
		toSerialize["primaryImageToken"] = o.PrimaryImageToken
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	if o.Budget != nil {
		toSerialize["budget"] = o.Budget
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformProjectItem struct {
	value *PlatformProjectItem
	isSet bool
}

func (v NullablePlatformProjectItem) Get() *PlatformProjectItem {
	return v.value
}

func (v *NullablePlatformProjectItem) Set(val *PlatformProjectItem) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformProjectItem) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformProjectItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformProjectItem(val *PlatformProjectItem) *NullablePlatformProjectItem {
	return &NullablePlatformProjectItem{value: val, isSet: true}
}

func (v NullablePlatformProjectItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformProjectItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


