/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformCompanyAddress struct for PlatformCompanyAddress
type PlatformCompanyAddress struct {
	Street *string `json:"street,omitempty"`
	Other *string `json:"other,omitempty"`
	Postalcode *string `json:"postalcode,omitempty"`
	City *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
}

// NewPlatformCompanyAddress instantiates a new PlatformCompanyAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformCompanyAddress() *PlatformCompanyAddress {
	this := PlatformCompanyAddress{}
	return &this
}

// NewPlatformCompanyAddressWithDefaults instantiates a new PlatformCompanyAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformCompanyAddressWithDefaults() *PlatformCompanyAddress {
	this := PlatformCompanyAddress{}
	return &this
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *PlatformCompanyAddress) GetStreet() string {
	if o == nil || o.Street == nil {
		var ret string
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCompanyAddress) GetStreetOk() (*string, bool) {
	if o == nil || o.Street == nil {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *PlatformCompanyAddress) HasStreet() bool {
	if o != nil && o.Street != nil {
		return true
	}

	return false
}

// SetStreet gets a reference to the given string and assigns it to the Street field.
func (o *PlatformCompanyAddress) SetStreet(v string) {
	o.Street = &v
}

// GetOther returns the Other field value if set, zero value otherwise.
func (o *PlatformCompanyAddress) GetOther() string {
	if o == nil || o.Other == nil {
		var ret string
		return ret
	}
	return *o.Other
}

// GetOtherOk returns a tuple with the Other field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCompanyAddress) GetOtherOk() (*string, bool) {
	if o == nil || o.Other == nil {
		return nil, false
	}
	return o.Other, true
}

// HasOther returns a boolean if a field has been set.
func (o *PlatformCompanyAddress) HasOther() bool {
	if o != nil && o.Other != nil {
		return true
	}

	return false
}

// SetOther gets a reference to the given string and assigns it to the Other field.
func (o *PlatformCompanyAddress) SetOther(v string) {
	o.Other = &v
}

// GetPostalcode returns the Postalcode field value if set, zero value otherwise.
func (o *PlatformCompanyAddress) GetPostalcode() string {
	if o == nil || o.Postalcode == nil {
		var ret string
		return ret
	}
	return *o.Postalcode
}

// GetPostalcodeOk returns a tuple with the Postalcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCompanyAddress) GetPostalcodeOk() (*string, bool) {
	if o == nil || o.Postalcode == nil {
		return nil, false
	}
	return o.Postalcode, true
}

// HasPostalcode returns a boolean if a field has been set.
func (o *PlatformCompanyAddress) HasPostalcode() bool {
	if o != nil && o.Postalcode != nil {
		return true
	}

	return false
}

// SetPostalcode gets a reference to the given string and assigns it to the Postalcode field.
func (o *PlatformCompanyAddress) SetPostalcode(v string) {
	o.Postalcode = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *PlatformCompanyAddress) GetCity() string {
	if o == nil || o.City == nil {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCompanyAddress) GetCityOk() (*string, bool) {
	if o == nil || o.City == nil {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *PlatformCompanyAddress) HasCity() bool {
	if o != nil && o.City != nil {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *PlatformCompanyAddress) SetCity(v string) {
	o.City = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *PlatformCompanyAddress) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCompanyAddress) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *PlatformCompanyAddress) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *PlatformCompanyAddress) SetCountry(v string) {
	o.Country = &v
}

func (o PlatformCompanyAddress) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Street != nil {
		toSerialize["street"] = o.Street
	}
	if o.Other != nil {
		toSerialize["other"] = o.Other
	}
	if o.Postalcode != nil {
		toSerialize["postalcode"] = o.Postalcode
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformCompanyAddress struct {
	value *PlatformCompanyAddress
	isSet bool
}

func (v NullablePlatformCompanyAddress) Get() *PlatformCompanyAddress {
	return v.value
}

func (v *NullablePlatformCompanyAddress) Set(val *PlatformCompanyAddress) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformCompanyAddress) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformCompanyAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformCompanyAddress(val *PlatformCompanyAddress) *NullablePlatformCompanyAddress {
	return &NullablePlatformCompanyAddress{value: val, isSet: true}
}

func (v NullablePlatformCompanyAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformCompanyAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


