/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformCampaignItemWrapper struct for PlatformCampaignItemWrapper
type PlatformCampaignItemWrapper struct {
	Items *[]PlatformCampaignItem `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewPlatformCampaignItemWrapper instantiates a new PlatformCampaignItemWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformCampaignItemWrapper() *PlatformCampaignItemWrapper {
	this := PlatformCampaignItemWrapper{}
	return &this
}

// NewPlatformCampaignItemWrapperWithDefaults instantiates a new PlatformCampaignItemWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformCampaignItemWrapperWithDefaults() *PlatformCampaignItemWrapper {
	this := PlatformCampaignItemWrapper{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PlatformCampaignItemWrapper) GetItems() []PlatformCampaignItem {
	if o == nil || o.Items == nil {
		var ret []PlatformCampaignItem
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItemWrapper) GetItemsOk() (*[]PlatformCampaignItem, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PlatformCampaignItemWrapper) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PlatformCampaignItem and assigns it to the Items field.
func (o *PlatformCampaignItemWrapper) SetItems(v []PlatformCampaignItem) {
	o.Items = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *PlatformCampaignItemWrapper) GetPagination() Pagination {
	if o == nil || o.Pagination == nil {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformCampaignItemWrapper) GetPaginationOk() (*Pagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *PlatformCampaignItemWrapper) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *PlatformCampaignItemWrapper) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o PlatformCampaignItemWrapper) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformCampaignItemWrapper struct {
	value *PlatformCampaignItemWrapper
	isSet bool
}

func (v NullablePlatformCampaignItemWrapper) Get() *PlatformCampaignItemWrapper {
	return v.value
}

func (v *NullablePlatformCampaignItemWrapper) Set(val *PlatformCampaignItemWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformCampaignItemWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformCampaignItemWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformCampaignItemWrapper(val *PlatformCampaignItemWrapper) *NullablePlatformCampaignItemWrapper {
	return &NullablePlatformCampaignItemWrapper{value: val, isSet: true}
}

func (v NullablePlatformCampaignItemWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformCampaignItemWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


