/*
Total API Reference

Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 

API version: 0.0.1
Contact: support@brand4impact.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package brand4impact

import (
	"encoding/json"
)

// PlatformNgoAddress struct for PlatformNgoAddress
type PlatformNgoAddress struct {
	Street *string `json:"street,omitempty"`
	Other *string `json:"other,omitempty"`
	Postalcode *string `json:"postalcode,omitempty"`
	City *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
}

// NewPlatformNgoAddress instantiates a new PlatformNgoAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformNgoAddress() *PlatformNgoAddress {
	this := PlatformNgoAddress{}
	return &this
}

// NewPlatformNgoAddressWithDefaults instantiates a new PlatformNgoAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformNgoAddressWithDefaults() *PlatformNgoAddress {
	this := PlatformNgoAddress{}
	return &this
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *PlatformNgoAddress) GetStreet() string {
	if o == nil || o.Street == nil {
		var ret string
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoAddress) GetStreetOk() (*string, bool) {
	if o == nil || o.Street == nil {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *PlatformNgoAddress) HasStreet() bool {
	if o != nil && o.Street != nil {
		return true
	}

	return false
}

// SetStreet gets a reference to the given string and assigns it to the Street field.
func (o *PlatformNgoAddress) SetStreet(v string) {
	o.Street = &v
}

// GetOther returns the Other field value if set, zero value otherwise.
func (o *PlatformNgoAddress) GetOther() string {
	if o == nil || o.Other == nil {
		var ret string
		return ret
	}
	return *o.Other
}

// GetOtherOk returns a tuple with the Other field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoAddress) GetOtherOk() (*string, bool) {
	if o == nil || o.Other == nil {
		return nil, false
	}
	return o.Other, true
}

// HasOther returns a boolean if a field has been set.
func (o *PlatformNgoAddress) HasOther() bool {
	if o != nil && o.Other != nil {
		return true
	}

	return false
}

// SetOther gets a reference to the given string and assigns it to the Other field.
func (o *PlatformNgoAddress) SetOther(v string) {
	o.Other = &v
}

// GetPostalcode returns the Postalcode field value if set, zero value otherwise.
func (o *PlatformNgoAddress) GetPostalcode() string {
	if o == nil || o.Postalcode == nil {
		var ret string
		return ret
	}
	return *o.Postalcode
}

// GetPostalcodeOk returns a tuple with the Postalcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoAddress) GetPostalcodeOk() (*string, bool) {
	if o == nil || o.Postalcode == nil {
		return nil, false
	}
	return o.Postalcode, true
}

// HasPostalcode returns a boolean if a field has been set.
func (o *PlatformNgoAddress) HasPostalcode() bool {
	if o != nil && o.Postalcode != nil {
		return true
	}

	return false
}

// SetPostalcode gets a reference to the given string and assigns it to the Postalcode field.
func (o *PlatformNgoAddress) SetPostalcode(v string) {
	o.Postalcode = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *PlatformNgoAddress) GetCity() string {
	if o == nil || o.City == nil {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoAddress) GetCityOk() (*string, bool) {
	if o == nil || o.City == nil {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *PlatformNgoAddress) HasCity() bool {
	if o != nil && o.City != nil {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *PlatformNgoAddress) SetCity(v string) {
	o.City = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *PlatformNgoAddress) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformNgoAddress) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *PlatformNgoAddress) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *PlatformNgoAddress) SetCountry(v string) {
	o.Country = &v
}

func (o PlatformNgoAddress) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Street != nil {
		toSerialize["street"] = o.Street
	}
	if o.Other != nil {
		toSerialize["other"] = o.Other
	}
	if o.Postalcode != nil {
		toSerialize["postalcode"] = o.Postalcode
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformNgoAddress struct {
	value *PlatformNgoAddress
	isSet bool
}

func (v NullablePlatformNgoAddress) Get() *PlatformNgoAddress {
	return v.value
}

func (v *NullablePlatformNgoAddress) Set(val *PlatformNgoAddress) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformNgoAddress) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformNgoAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformNgoAddress(val *PlatformNgoAddress) *NullablePlatformNgoAddress {
	return &NullablePlatformNgoAddress{value: val, isSet: true}
}

func (v NullablePlatformNgoAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformNgoAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


